# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a32147d35d9c9acc079b375104786d970a6cd5eedc02287a5e6f9935e4ac65d8852f17046b8cde4c72ebfa4c511929f06f9714f89d8eec2de08c9151ee2f85aa

test:
  secret_key_base: 9a1f4573452b3e6922db0da0886d4dd99e6f244a490d95836440b6d9aa336e81a4c2e1beb2f829a4f9088c2c3764d352322b858e617201fc23a769c0212e5df1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
